### ISSUE TITLE
Storybook: Resolución de problemas en runtime

### ISSUE THREAD

**Issue by erikgiovani** [cuentoneta/cuentoneta#417]
## Descripción
Este issue agrupa tareas relacionadas a la resolución de problemas, la refactorización de las stories de los componentes que no se visualizan bien en storybook y la creación de las stories de los componentes faltantes.

## Metodología

La resolución de los issues de sección subsiguiente "Tareas -> Tooling" son condiciones necesarias para poder efectuar posteriormente las modificaciones que solucionan los problemas con los tests.

### Tooling

- [x] #944 
- [x] Agregado de build de Storybook y despliegue a CI/CD

### Stories
- [x] create: audio-recording-widget
- [ ] create: author-navigation-frame
- [ ] create: badge
- [ ] create: epigraph
- [ ] create: media-resource-tags
- [ ] create: media-resource
- [ ] create: navigable-publication-teaser
- [ ] create: navigable-story-teaser
- [ ] create: portable-text-styles-marks-serializer
- [ ] create: resource
- [ ] create: share-content
- [ ] create:  story-card-skeleton
- [ ] create: story-card
- [ ] create:  story-edition-date-label
- [ ] create: storylist-navigation-frame
- [ ] create: svg-icon
- [ ] create: youtube-video-widget
- [ ] create: home
- [ ] create: about
- [ ] create: author
- [ ] create: dmca
- [ ] create: story
- [ ] create: storylist
- [ ] fix: bio-summary-card
- [ ] fix: story-navigation-bar
- [ ] fix: footer
- [ ] fix: header
- [ ] fix: publication-card
- [ ] fix: story-card-content
- [ ] fix: storylist-card.component

### Revisar:
- [ ] portable-text-parser
- [ ] publication-card
- [ ] space-recording-widget
- [ ] story-card-content
- [ ] storylist-card-component

### Criterios de aceptación

Cada storie se debe de hacer como un issue independiente.

### Recursos

* [Cómo usar Storybook en Angular](https://storybook.js.org/tutorials/intro-to-storybook/angular/es/get-started/)
* [Deploy Storybook de La Cuentoneta](https://cuentoneta-storybook.vercel.app/)

#### Ejemplos de instancias de Storybook de otros proyectos
* https://sb-primitives.radix-ng.com/?path=/docs/primitives-accordion--docs
* https://storybook.js.org/showcase
* https://www.uxpin.com/studio/blog/storybook-examples/
* https://storybook.js.org/showcase/adobe-spectrum-web-components
* https://circuit.sumup.com/

**Comment by rolivencia** [comment]
@ErikGIovani, ¿podrás chequear si es que esta lista es correcta a la fecha de hoy? Luego procedemos a generar issues individuales por cada componente.

**Comment by ErikGIovani** [comment]
> @ErikGIovani, ¿podrás chequear si es que esta lista es correcta a la fecha de hoy? Luego procedemos a generar issues individuales por cada componente.

Listo 👍 agregué unos nuevos para fixear, quieres que hagamos stories de todos los componentes y paginas?

**Comment by rolivencia** [comment]
> > @ErikGIovani, ¿podrás chequear si es que esta lista es correcta a la fecha de hoy? Luego procedemos a generar issues individuales por cada componente.
> 
> Listo 👍 agregué unos nuevos para fixear, quieres que hagamos stories de todos los componentes y paginas?

Sí, adelante. Por favor no olvides agregarles el tab `✍️ bosquejo`, el cual corresponde ahora a todos los issues cuya descripción está pendiente de ser detallada. Una vez los vayamos completando procedemos a removerlo.

**Comment by ErikGIovani** [comment]
> > > @ErikGIovani, ¿podrás chequear si es que esta lista es correcta a la fecha de hoy? Luego procedemos a generar issues individuales por cada componente.
> > 
> > 
> > Listo 👍 agregué unos nuevos para fixear, quieres que hagamos stories de todos los componentes y paginas?
> 
> Sí, adelante. Por favor no olvides agregarles el tab `✍️ bosquejo`, el cual corresponde ahora a todos los issues cuya descripción está pendiente de ser detallada. Una vez los vayamos completando procedemos a removerlo.

Estuve revisando y el deploy que tenemos de storybook no tiene las stories que puse en la sección **Revisar:** de este issue

**Comment by rolivencia** [comment]
¿Te parece que nos centremos en todos los issues relacionados a testing para este hito y procedemos a trabajar en este en el próximo? @ErikGIovani. El trabajo a realizar ya está identificado.

**Comment by ErikGIovani** [comment]
> ¿Te parece que nos centremos en todos los issues relacionados a testing para este hito y procedemos a trabajar en este en el próximo? @ErikGIovani. El trabajo a realizar ya está identificado.
> 
> Conservamos para este hito #944 y luego procedemos con las tareas individuales, transformándolas en issues progresivamente.

Suena excelente 👍

**Comment by rolivencia** [comment]
Queda desbloqueado este issue para trabajarlo a futuro.

**Comment by rolivencia** [comment]
Cierro el issue debido a que la incorporación de los nuevos componentes para la v3 traerá aparejada la generación de los correspondientes stories para cada uno.
