### ISSUE TITLE
Tipar resultados de queries de Sanity

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#697]
### Descripción

Existen consultas hacia Sanity hechas en los archivos `story.service.ts`, `storylist.service.ts`, `content.service.ts` y `author.service.ts` dentro del árbol de directorios de `/api`, los cuales pertenecen al "backend" de la aplicación.

Se requiere tipar los resultados de estas consultas para fortalecer la cobertura de tipado que posee el proyecto mediante la incorporación de Sanity TypeGen para la tarea. Deben evaluarse las consultas escritas en los archivos `*.service.ts` y `*.query.ts` y proceder al tipado de las mismas.

### Criterios de aceptación

- Los resultados de las consultas hechas mediante el método `client.fetch()` en `story.service.ts`, `storylist.service.ts`, `content.service.ts` y `author.service.ts` deben ser tipados.
- Todas las consultas en GROQ definidas en los archivos `/api/**/*.service.ts` deben pasar a estar definidas en los archivos `/api/**/*.query.ts` correspondientes.
- Adicionalmente debe chequearse la nomenclatura de las funciones visitadas como parte de este issue, aprovechando la oportunidad para brindar mayor coherencia a los nombres de las funciones definidas en los services.

### Tareas

- [x] Agregar Sanity TypeGen para generación automática de tipos para queries. El primer sub-issue de esta lista que sea resuelto debe abordar la tarea de agregar la infraestructura necesaria para ejecutar Sanity TypeGen. (abordado en #832)
- [x] Agregar tipado para fetches en `/api/story/story.service.ts`
  - [x] #832
  - [x] #835
- [x] Agregar tipado para fetches en `/api/author/author.service.ts`
  - [x] #833
- [x] Agregar tipado para fetches en `/api/content.service.ts`
    - [x] #834
- [x]  Agregar tipado para fetches en `/api/storylist.service.ts`
    - [x] #836
    - [x] #837
- [x] #866

### Recursos

* Curso en Sanity Learn sobre tipado de queries en GROQ: https://www.sanity.io/learn/course/typescripted-content/generating-type-for-groq-query-results.

**Comment by Addin** [comment]
Asignado el issue a @luz-ojeda.

**Comment by rolivencia** [comment]
Agregado el recurso sugerido por @franciscohanna92. cc @luz-ojeda.

**Comment by luz-ojeda** [comment]
Lo tomo

**Comment by luz-ojeda** [comment]
Después de todo esto estaría bueno revisar `src/api/sanity/types.ts` para reducir repetición. Si bien es donde se generan los tipos automáticamente si agregás algo manualmente y luego corrés `sanity typegen generate` no lo remueve.

No estoy segura del todo si había opción de evitar a priori tanta repetición, no creo de ver que es _relativamente_ rudimentaria la herramienta. Pero dejo esto por acá para cuando se cierre la issue, generar alguna otra así queda a futuro.

**Comment by rolivencia** [comment]
Se me ocurre como alternativa, para evitar modificaciones, el generar el archivo de types como parte del script de preinstall ejecutando `sanity typegen generate` y marcando el archivo como ignorado por git.

**Comment by rolivencia** [comment]
Procedo a cerrar el epic, ya que todos los issues fueron completados. Gran trabajo @luz-ojeda 👏
