### ISSUE TITLE
Carousel para campañas de contenido

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#913]
## Descripción
Se requiere la implementación de un componente carousel para poder publicitar, en determinados momentos, secciones de contenido en la plataforma. Para el desarrollo de esta característica debe tomarse como ejemplo visual el carousel que se encuentra disponible en la landing page de la plataforma [Wattpad](https://www.wattpad.com/).

Los elementos que deben de mostrarse en las distintas slides de un carousel serán nuevas entidades dentro del modelo de dominio de la plataforma, los cuales llevarán el nombre de `ContentCampaign`, conteniendo cada uno información relevante a piezas de contenido publicitadas en la web. Debido a que esta característica para la plataforma debe de ser visualmente _responsive_, se requerirá el soporte de textos e imágenes para adaptar la visualización a distintos tamaños de pantalla.

En el aspecto arquitectónico deberá de utilizarse la infraestructura existente de `ContentController` y `ContentService` en el _backend_ para devolver esta información hacia el frontend.

## Requerimientos de usabilidad y visualización
Se adjuntan a continuación ejemplos visuales de la idea que se trata de capturar desde [Wattpad](https://www.wattpad.com/) y de la implementación de un prototipo de la característica, disponible en la rama `test-carousel` del proyecto.

Para la visualización en viewports `xs` y `sm` el tamaño de las imágenes debe ser de `540px por 220px`, mientras que para viewports `md` y superiores el tamaño de las imágenes debe ser de `960px por 280px`. De manera análoga deben determinarse un límite superior para la cantidad de caracteres de los títulos y subtítulos en las dos versiones, evitando el ingreso de textos que provoquen un salto de línea al visualizar una slide del carousel.

Para reforzar los requerimientos anteriores se debe:
- Establecer el título con un máximo de `32` caracteres para la versión mobile (viewports `xs` y `sm`) y de `40` caracteres para viewports desktop y tablet grande (viewport `md` y superiores). Agregar regla de validación en Sanity Studio.
- Establecer el subtítulo con un máximo de `36` caracteres para la versión mobile (viewports `xs` y `sm`) y de `48` caracteres para viewports desktop y tablet grande (viewport `md` y superiores). Agregar regla de validación en Sanity Studio.
- Establecer el `text-overflow` en el frontend en modo `ellipsis`, a fin de poder evitar saltos de línea en casos límite.
- Documentar en el repositorio y [restringir en Sanity Studio](https://stackoverflow.com/questions/58567054/how-can-i-validate-the-dimensions-of-an-uploaded-image-in-sanity) los tamaños de imagen admitidos.

#### Versión desktop Wattpad
https://github.com/user-attachments/assets/e80bf7e6-3a6a-4215-addf-182470cb116d

#### Versión mobile Wattpad
https://github.com/user-attachments/assets/66f5d3aa-3573-4505-8bff-0a891bf4681e

#### Prototipo desktop Cuentoneta
https://github.com/user-attachments/assets/9877149d-c7bd-4bfc-8988-af63a07b5aeb

#### Prototipo mobile Cuentoneta
https://github.com/user-attachments/assets/3887a67f-c391-4aec-ba61-22892d37a267

## Modelo de dominio
Esta característica debe soportar la visualización de las imágenes del carousel adaptadas a distintos tamaños de pantalla. Para ello el modelo de dominio que representa a una campaña de contenido debe poseer la información del contenido adaptado a los distintos viewports que soporta la plataforma, los cuales son los tamaños de pantalla `xs` y `md` definidos en la configuración de Tailwind.

```typescript

/**
 * Tipo que representa los diferentes viewports soportados por la aplicación para las campañas de contenido, a fin de
 * proveer una experiencia responsive y adaptable para su visualización.
 */
export const ContentCampaignViewportKeys = ['xs', 'md'];
export type ContentCampaignViewport = (typeof ContentCampaignViewportKeys)[number];

/**
 * Constante que indica, para los viewports soportados, las longitudes máximas asignables a los títulos y subtítulos
 * de las campañas de contenido y las dimensiones de las imágenes asociadas a cada una de ellas.
 */
export const viewportElementSizes = Object.freeze({
	xs: {
		title: 32,
		subtitle: 36,
		imageWidth: 540,
		imageHeight: 220,
	},
	md: {
		title: 40,
		subtitle: 60,
		imageWidth: 960,
		imageHeight: 280,
	},
});

/**
 * Interface que define al objeto de dominio que representa una campaña de contenido en la plataforma.
 */
export interface ContentCampaign {
	title: string;
	slug: string;
	description: TextBlockContent[];
	url: string;
	contents: {
		[key in ContentCampaignViewport]: {
			title: TextBlockContent[];
			subtitle: TextBlockContent[];
			imageUrl: string;
			imageWidth: number;
			imageHeight: number;
		};
	};
}
```

### Dominio
- [x] #1020
- [x] #1026

### Orígenes de datos (Sanity)
- [x] #1022

### Backend
- [x] #1024

### Frontend
- [x] #1038
- [x] #1036
- [x] #1040
- [x] #1045
- [x] #1049
- [x] #1063
- [x] Refinar tamaños de tipografías y text copies para landing page

### Documentación
- [x] Documentar modelo de dominio
- [x] Documentar requerimientos respecto de las campañas de contenido, los cuales deben hacerse extensivos a colaboradores internos y externos que deseen generar una campana de contenido en la plataforma.
