### ISSUE TITLE
Eliminar funcionalidad de grid dinámica del proyecto

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#960]
### Descripción

En pos de simplificar ... y a la vez preparar los componentes de la aplicación para soportar el nuevo sistema de diseño...
[... A DESARROLLAR]

### Tareas
- [ ] Agregar atributo `publications` al schema storylist
- [ ] Generar script para copiar contenido `gridConfig.publications` a `publications` en todas las storylists
- [ ] Actualizar modelos de dominio, eliminando la propiedad `gridConfig` de la interface `StorylistBase`.
- [ ] Actualizar queries GROQ relacionadas a storylist, eliminando la obtención de estas propiedades.
- [ ] Actualizar script `set-environment.ts`
- [ ] Actualizar interface de `environment.ts`
- [ ] Actualizar schema de Sanity, eliminando las propiedades relacionadas a `gridConfig`

### Issues relacionados
- #750
